/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasetRouteImport } from './routes/dataset'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as MethodRouteImport } from './routes/method'
import { Route as RetrievalRouteImport } from './routes/retrieval'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetRoute = DatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrievalRoute = RetrievalRouteImport.update({
  id: '/retrieval',
  path: '/retrieval',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dataset': typeof DatasetRoute
  '/evaluation': typeof EvaluationRoute
  '/method': typeof MethodRoute
  '/retrieval': typeof RetrievalRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dataset': typeof DatasetRoute
  '/evaluation': typeof EvaluationRoute
  '/method': typeof MethodRoute
  '/retrieval': typeof RetrievalRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dataset': typeof DatasetRoute
  '/evaluation': typeof EvaluationRoute
  '/method': typeof MethodRoute
  '/retrieval': typeof RetrievalRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dataset'
    | '/evaluation'
    | '/method'
    | '/retrieval'
    | '/api/public/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dataset'
    | '/evaluation'
    | '/method'
    | '/retrieval'
    | '/api/public/ingest'
  id:
    | '__root__'
    | '/'
    | '/dataset'
    | '/evaluation'
    | '/method'
    | '/retrieval'
    | '/api/public/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetRoute: typeof DatasetRoute
  EvaluationRoute: typeof EvaluationRoute
  MethodRoute: typeof MethodRoute
  RetrievalRoute: typeof RetrievalRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset': {
      id: '/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrieval': {
      id: '/retrieval'
      path: '/retrieval'
      fullPath: '/retrieval'
      preLoaderRoute: typeof RetrievalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetRoute: DatasetRoute,
  EvaluationRoute: EvaluationRoute,
  MethodRoute: MethodRoute,
  RetrievalRoute: RetrievalRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
